using System.Text;
using OtelEvents.Schema.Models;

namespace OtelEvents.Schema.CodeGen;

/// <summary>
/// Generates C# source code from a <see cref="SchemaDocument"/>.
/// Produces LoggerMessage extensions, metric instruments, typed Emit methods, and enum types.
/// </summary>
public sealed class CodeGenerator
{
    private const string AutoGeneratedHeader = """
        // <auto-generated>
        // Generated by otel-events Code Generator
        // DO NOT EDIT — changes will be overwritten on next build
        // </auto-generated>
        
        #nullable enable
        
        """;

    /// <summary>
    /// Generates all C# source files from a schema document.
    /// </summary>
    /// <param name="doc">The parsed schema document.</param>
    /// <returns>A list of generated source files.</returns>
    public IReadOnlyList<GeneratedFile> GenerateFromSchema(SchemaDocument doc)
    {
        var files = new List<GeneratedFile>();

        // Collect all enums: top-level + inline from event fields
        var allEnums = CollectAllEnums(doc);
        foreach (var enumDef in allEnums)
        {
            files.Add(GenerateEnumFile(doc.Schema.Namespace, enumDef));
        }

        // Generate events file if there are events
        if (doc.Events.Count > 0)
        {
            files.Add(GenerateEventsFile(doc));
        }

        // Generate DI service registration extension (only for DI mode with metrics)
        var hasAnyMetrics = doc.Events.Any(e => e.Metrics.Count > 0);
        if (doc.Schema.MeterLifecycle == MeterLifecycle.DI && hasAnyMetrics)
        {
            files.Add(GenerateServiceCollectionExtensionFile(doc));
        }

        return files;
    }

    // ═══════════════════════════════════════════════════════════════
    // ENUM GENERATION
    // ═══════════════════════════════════════════════════════════════

    private static GeneratedFile GenerateEnumFile(string ns, EnumDefinition enumDef)
    {
        var enumName = NamingHelper.ToPascalCase(enumDef.Name);
        var sb = new StringBuilder();

        sb.Append(AutoGeneratedHeader);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // Enum type
        if (enumDef.Description is not null)
        {
            sb.AppendLine($"/// <summary>{EscapeXmlComment(enumDef.Description)}</summary>");
        }
        sb.AppendLine($"public enum {enumName}");
        sb.AppendLine("{");
        foreach (var value in enumDef.Values)
        {
            var sanitized = NamingHelper.SanitizeIdentifier(value);
            sb.AppendLine($"    {sanitized},");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // ToStringFast extension
        sb.AppendLine($"/// <summary>Fast enum-to-string conversion (no allocation).</summary>");
        sb.AppendLine($"public static class {enumName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string ToStringFast(this {enumName} value) => value switch");
        sb.AppendLine("    {");
        foreach (var value in enumDef.Values)
        {
            var sanitized = NamingHelper.SanitizeIdentifier(value);
            sb.AppendLine($"        {enumName}.{sanitized} => \"{EscapeString(value)}\",");
        }
        sb.AppendLine("        _ => value.ToString(),");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return new GeneratedFile($"{enumName}.g.cs", sb.ToString());
    }

    // ═══════════════════════════════════════════════════════════════
    // EVENTS FILE GENERATION
    // ═══════════════════════════════════════════════════════════════

    private static GeneratedFile GenerateEventsFile(SchemaDocument doc)
    {
        var schemaName = NamingHelper.SanitizeIdentifier(doc.Schema.Name);
        var ns = doc.Schema.Namespace;
        var meterName = doc.Schema.MeterName ?? ns;
        var hasAnyMetrics = doc.Events.Any(e => e.Metrics.Count > 0);
        var hasTransactions = doc.Events.Any(e => e.EventType != EventType.Event);
        var isDiMode = doc.Schema.MeterLifecycle == MeterLifecycle.DI;

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader);

        // Using statements
        sb.AppendLine("using System;");
        if (hasAnyMetrics)
        {
            sb.AppendLine("using System.Diagnostics.Metrics;");
        }
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        if (hasTransactions)
        {
            sb.AppendLine("using OtelEvents.Causality;");
        }
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // 0. Metadata class (schema version + name constants)
        GenerateMetadataClass(sb, schemaName, doc);
        sb.AppendLine();

        // 1. Event constants classes (one per event)
        foreach (var evt in doc.Events)
        {
            GenerateEventConstantsClass(sb, evt, doc.Schema.Prefix);
            sb.AppendLine();
        }

        // 2. LoggerMessage partial class
        GenerateLoggerExtensionsClass(sb, schemaName, doc);
        sb.AppendLine();

        // 3. Metrics class (only if any event has metrics)
        if (hasAnyMetrics)
        {
            if (isDiMode)
            {
                GenerateDIMetricsClass(sb, schemaName, meterName, doc);
            }
            else
            {
                GenerateMetricsClass(sb, schemaName, meterName, doc);
            }
            sb.AppendLine();
        }

        // 4. Emit extension methods class
        GenerateEventExtensionsClass(sb, schemaName, doc.Events, hasAnyMetrics, isDiMode);

        return new GeneratedFile($"{schemaName}Events.g.cs", sb.ToString());
    }

    // ── Metadata Class ────────────────────────────────────────────

    private static void GenerateMetadataClass(
        StringBuilder sb,
        string schemaName,
        SchemaDocument doc)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Schema metadata for {schemaName}.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {schemaName}Metadata");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>The schema version from the YAML definition.</summary>");
        sb.AppendLine($"    public const string SchemaVersion = \"{EscapeString(doc.Schema.Version)}\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>The schema name from the YAML definition.</summary>");
        sb.AppendLine($"    public const string SchemaName = \"{EscapeString(doc.Schema.Name)}\";");
        sb.AppendLine("}");
    }

    // ── Event Constants Classes ─────────────────────────────────────

    /// <summary>
    /// Computes the event code string for a given event.
    /// Returns "{prefix}-{id}" if a prefix is available, or just "{id}" otherwise.
    /// Per-event prefix overrides the schema-level prefix.
    /// </summary>
    internal static string ComputeEventCode(EventDefinition evt, string? schemaPrefix)
    {
        var effectivePrefix = evt.Prefix ?? schemaPrefix;
        return effectivePrefix is not null
            ? $"{effectivePrefix}-{evt.Id}"
            : evt.Id.ToString();
    }

    private static void GenerateEventConstantsClass(
        StringBuilder sb,
        EventDefinition evt,
        string? schemaPrefix)
    {
        var className = NamingHelper.ToMethodName(evt.Name);
        var code = ComputeEventCode(evt, schemaPrefix);

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Constants for the {className} event.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {className}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>The event code string (prefix + numeric ID).</summary>");
        sb.AppendLine($"    public const string Code = \"{EscapeString(code)}\";");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>The numeric event ID.</summary>");
        sb.AppendLine($"    public const int NumericId = {evt.Id};");
        sb.AppendLine();
        sb.AppendLine($"    /// <summary>The event name.</summary>");
        sb.AppendLine($"    public const string EventName = \"{EscapeString(className)}\";");
        sb.AppendLine("}");
    }

    // ── LoggerMessage Extensions ───────────────────────────────────

    private static void GenerateLoggerExtensionsClass(
        StringBuilder sb,
        string schemaName,
        SchemaDocument doc)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// LoggerMessage methods for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {schemaName}LoggerExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < doc.Events.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            GenerateLoggerMessageMethod(sb, doc.Events[i], doc.Schema.Prefix);
        }

        sb.AppendLine("}");
    }

    private static void GenerateLoggerMessageMethod(
        StringBuilder sb,
        EventDefinition evt,
        string? schemaPrefix)
    {
        var methodName = NamingHelper.ToMethodName(evt.Name);
        var logLevel = TypeMapper.ToLogLevel(evt.Severity);
        var eventCode = ComputeEventCode(evt, schemaPrefix);

        // [LoggerMessage] attribute
        sb.AppendLine($"    [LoggerMessage(");
        sb.AppendLine($"        EventId = {evt.Id},");
        sb.AppendLine($"        EventName = \"{EscapeString(eventCode)}\",");
        sb.AppendLine($"        Level = {logLevel},");
        sb.AppendLine($"        Message = \"{EscapeString(evt.Message)}\")]");

        // Method signature
        sb.Append($"    public static partial void {methodName}(this ILogger logger");
        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");
    }

    // ── Metrics Class ──────────────────────────────────────────────

    private static void GenerateMetricsClass(
        StringBuilder sb,
        string schemaName,
        string meterName,
        SchemaDocument doc)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Metric instruments for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {schemaName}Metrics");
        sb.AppendLine("{");

        // Meter instance
        sb.AppendLine($"    private static readonly Meter s_meter = new Meter(\"{EscapeString(meterName)}\", \"{EscapeString(doc.Schema.Version)}\");");
        sb.AppendLine();

        var isFirst = true;
        foreach (var evt in doc.Events)
        {
            foreach (var metric in evt.Metrics)
            {
                if (!isFirst) sb.AppendLine();
                isFirst = false;

                GenerateMetricField(sb, metric);
            }
        }

        sb.AppendLine("}");
    }

    private static void GenerateMetricField(StringBuilder sb, MetricDefinition metric)
    {
        var clrType = TypeMapper.GetMetricClrType(metric.Type);
        var createMethod = TypeMapper.GetInstrumentCreationMethod(metric.Type);
        var fieldName = NamingHelper.ToMetricFieldName(metric.Name);
        var instrumentType = GetInstrumentTypeName(metric.Type);

        sb.Append($"    public static readonly {instrumentType}<{clrType}> {fieldName} =");
        sb.AppendLine();

        // Build creation call with optional unit and description
        sb.Append($"        s_meter.{createMethod}<{clrType}>(\"{EscapeString(metric.Name)}\"");

        if (metric.Unit is not null || metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Unit ?? "")}\"");
        }

        if (metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Description)}\"");
        }

        sb.AppendLine(");");
    }

    // ── DI Metrics Class ───────────────────────────────────────────

    private static void GenerateDIMetricsClass(
        StringBuilder sb,
        string schemaName,
        string meterName,
        SchemaDocument doc)
    {
        var className = $"{schemaName}Metrics";

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// DI-friendly metric instruments for {schemaName} events.");
        sb.AppendLine("/// Inject via <c>IMeterFactory</c> for disposable meter lifecycle.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public sealed class {className} : IDisposable");
        sb.AppendLine("{");

        // Private Meter field
        sb.AppendLine("    private readonly Meter _meter;");
        sb.AppendLine();

        // Public instrument properties
        foreach (var evt in doc.Events)
        {
            foreach (var metric in evt.Metrics)
            {
                GenerateDIMetricProperty(sb, metric);
            }
        }
        sb.AppendLine();

        // Constructor with IMeterFactory
        sb.AppendLine($"    public {className}(IMeterFactory meterFactory)");
        sb.AppendLine("    {");
        sb.AppendLine($"        _meter = meterFactory.Create(\"{EscapeString(meterName)}\");");

        foreach (var evt in doc.Events)
        {
            foreach (var metric in evt.Metrics)
            {
                GenerateDIMetricAssignment(sb, metric);
            }
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // IDisposable
        sb.AppendLine("    /// <summary>Disposes the underlying Meter.</summary>");
        sb.AppendLine("    public void Dispose() => _meter?.Dispose();");
        sb.AppendLine("}");
    }

    private static void GenerateDIMetricProperty(StringBuilder sb, MetricDefinition metric)
    {
        var clrType = TypeMapper.GetMetricClrType(metric.Type);
        var instrumentType = GetInstrumentTypeName(metric.Type);
        var propertyName = NamingHelper.ToMetricPropertyName(metric.Name);

        if (metric.Description is not null)
        {
            sb.AppendLine($"    /// <summary>{EscapeXmlComment(metric.Description)}</summary>");
        }
        sb.AppendLine($"    public {instrumentType}<{clrType}> {propertyName} {{ get; }}");
    }

    private static void GenerateDIMetricAssignment(StringBuilder sb, MetricDefinition metric)
    {
        var clrType = TypeMapper.GetMetricClrType(metric.Type);
        var createMethod = TypeMapper.GetInstrumentCreationMethod(metric.Type);
        var propertyName = NamingHelper.ToMetricPropertyName(metric.Name);

        sb.Append($"        {propertyName} = _meter.{createMethod}<{clrType}>(\"{EscapeString(metric.Name)}\"");

        if (metric.Unit is not null || metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Unit ?? "")}\"");
        }

        if (metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Description)}\"");
        }

        sb.AppendLine(");");
    }

    // ── DI Service Registration Extension ──────────────────────────

    private static GeneratedFile GenerateServiceCollectionExtensionFile(SchemaDocument doc)
    {
        var schemaName = NamingHelper.SanitizeIdentifier(doc.Schema.Name);
        var ns = doc.Schema.Namespace;
        var className = $"{schemaName}Metrics";
        var extensionClassName = $"{className}ServiceCollectionExtensions";

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader);

        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();

        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// DI registration extension for <see cref=\"{className}\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {extensionClassName}");
        sb.AppendLine("{");
        sb.AppendLine($"    /// <summary>Registers <see cref=\"{className}\"/> as a singleton.</summary>");
        sb.AppendLine($"    public static IServiceCollection Add{className}(this IServiceCollection services)");
        sb.AppendLine($"        => services.AddSingleton<{className}>();");
        sb.AppendLine("}");

        return new GeneratedFile($"{extensionClassName}.g.cs", sb.ToString());
    }

    // ── Event Extensions (Emit methods) ────────────────────────────

    private static void GenerateEventExtensionsClass(
        StringBuilder sb,
        string schemaName,
        List<EventDefinition> events,
        bool hasAnyMetrics,
        bool isDiMode = false)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Typed extension methods combining logging and metrics for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {schemaName}EventExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < events.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            GenerateEmitMethod(sb, schemaName, events[i], hasAnyMetrics, isDiMode);
        }

        sb.AppendLine("}");
    }

    private static void GenerateEmitMethod(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        bool hasAnyMetrics,
        bool isDiMode = false)
    {
        var methodName = NamingHelper.ToMethodName(evt.Name);

        // Dispatch to specialized generators based on event type
        switch (evt.EventType)
        {
            case EventType.Start:
                GenerateStartEmitMethod(sb, schemaName, evt, methodName, isDiMode);
                break;
            case EventType.Success:
                GenerateOutcomeEmitMethod(sb, schemaName, evt, methodName, isDiMode, isSuccess: true);
                break;
            case EventType.Failure:
                GenerateOutcomeEmitMethod(sb, schemaName, evt, methodName, isDiMode, isSuccess: false);
                break;
            default:
                GenerateDefaultEmitMethod(sb, schemaName, evt, methodName, hasAnyMetrics, isDiMode);
                break;
        }
    }

    private static void GenerateDefaultEmitMethod(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        string methodName,
        bool hasAnyMetrics,
        bool isDiMode)
    {
        var emitMethodName = $"Emit{methodName}";

        // Method signature
        sb.Append($"    public static void {emitMethodName}(this ILogger logger");

        // In DI mode, inject metrics instance if event has metrics
        if (isDiMode && evt.Metrics.Count > 0)
        {
            sb.Append($", {schemaName}Metrics metrics");
        }

        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // Call LoggerMessage method
        sb.Append($"        {schemaName}LoggerExtensions.{methodName}(logger");
        AppendFieldArguments(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");

        // Record metrics
        if (evt.Metrics.Count > 0)
        {
            sb.AppendLine();
            GenerateMetricRecording(sb, schemaName, evt, isDiMode);
        }

        sb.AppendLine("    }");
    }

    private static void GenerateStartEmitMethod(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        string methodName,
        bool isDiMode)
    {
        var beginMethodName = $"Begin{methodName}";

        // Return OtelEventsTransactionScope instead of void
        sb.Append($"    public static OtelEventsTransactionScope {beginMethodName}(this ILogger logger");

        if (isDiMode && evt.Metrics.Count > 0)
        {
            sb.Append($", {schemaName}Metrics metrics");
        }

        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // Call LoggerMessage method
        sb.Append($"        {schemaName}LoggerExtensions.{methodName}(logger");
        AppendFieldArguments(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");

        // Record metrics
        if (evt.Metrics.Count > 0)
        {
            sb.AppendLine();
            GenerateMetricRecording(sb, schemaName, evt, isDiMode);
        }

        // Begin transaction scope
        sb.AppendLine();
        sb.AppendLine($"        return OtelEventsTransactionScope.Begin(\"{EscapeString(evt.Name)}\");");

        sb.AppendLine("    }");
    }

    private static void GenerateOutcomeEmitMethod(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        string methodName,
        bool isDiMode,
        bool isSuccess)
    {
        var emitMethodName = $"Emit{methodName}";

        // Standard void return
        sb.Append($"    public static void {emitMethodName}(this ILogger logger");

        if (isDiMode && evt.Metrics.Count > 0)
        {
            sb.Append($", {schemaName}Metrics metrics");
        }

        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // Call LoggerMessage method
        sb.Append($"        {schemaName}LoggerExtensions.{methodName}(logger");
        AppendFieldArguments(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");

        // Record metrics
        if (evt.Metrics.Count > 0)
        {
            sb.AppendLine();
            GenerateMetricRecording(sb, schemaName, evt, isDiMode);
        }

        // Close the parent transaction scope
        if (evt.ParentEvent is not null)
        {
            sb.AppendLine();
            var resolveMethod = isSuccess ? "TryComplete" : "TryFail";
            sb.AppendLine($"        OtelEventsTransactionScope.{resolveMethod}(\"{EscapeString(evt.ParentEvent)}\", \"{EscapeString(evt.Name)}\");");
        }

        sb.AppendLine("    }");
    }

    private static void GenerateMetricRecording(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        bool isDiMode = false)
    {
        // Build TagList if any metric has labels
        var hasLabels = evt.Metrics.Any(m => m.Labels is { Count: > 0 });
        if (hasLabels)
        {
            var allLabels = evt.Metrics
                .Where(m => m.Labels is not null)
                .SelectMany(m => m.Labels!)
                .Distinct()
                .ToList();

            sb.AppendLine("        var tags = new TagList");
            sb.AppendLine("        {");
            foreach (var label in allLabels)
            {
                var paramName = NamingHelper.ToCamelCase(NamingHelper.SanitizeIdentifier(label));
                sb.AppendLine($"            {{ \"{EscapeString(label)}\", {paramName} }},");
            }
            sb.AppendLine("        };");
        }

        foreach (var metric in evt.Metrics)
        {
            var tagsSuffix = hasLabels && metric.Labels is { Count: > 0 } ? ", tags" : "";

            // Resolve the accessor prefix: instance property in DI mode, static field in static mode
            string accessor;
            if (isDiMode)
            {
                var propertyName = NamingHelper.ToMetricPropertyName(metric.Name);
                accessor = $"metrics.{propertyName}";
            }
            else
            {
                var fieldName = NamingHelper.ToMetricFieldName(metric.Name);
                accessor = $"{schemaName}Metrics.{fieldName}";
            }

            if (metric.Type == MetricType.Counter)
            {
                sb.AppendLine($"        {accessor}.Add(1{tagsSuffix});");
            }
            else if (metric.Type == MetricType.Histogram)
            {
                // Try to match a field by the last segment of the metric name.
                // Since all fields are strings, use double.TryParse() to convert.
                var lastSegment = NamingHelper.GetLastSegment(metric.Name);
                var matchingField = evt.Fields.FirstOrDefault(f =>
                    f.Name.Equals(lastSegment, StringComparison.OrdinalIgnoreCase));

                if (matchingField is not null)
                {
                    var paramName = NamingHelper.ToCamelCase(matchingField.Name);
                    sb.AppendLine($"        if (double.TryParse({paramName}, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var {paramName}Value))");
                    sb.AppendLine($"            {accessor}.Record({paramName}Value{tagsSuffix});");
                }
                else
                {
                    sb.AppendLine($"        {accessor}.Record(1{tagsSuffix});");
                }
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // HELPERS
    // ═══════════════════════════════════════════════════════════════

    private static List<EnumDefinition> CollectAllEnums(SchemaDocument doc)
    {
        // Only collect top-level enums; inline field enums are no longer supported
        // since all fields are strings.
        return new List<EnumDefinition>(doc.Enums);
    }

    private static void AppendFieldParameters(
        StringBuilder sb,
        List<FieldDefinition> fields,
        bool hasException)
    {
        foreach (var field in fields)
        {
            sb.Append(", ");
            var paramName = NamingHelper.ToCamelCase(field.Name);

            if (field.Required)
            {
                sb.Append($"string {paramName}");
            }
            else
            {
                sb.Append($"string? {paramName} = null");
            }
        }

        if (hasException)
        {
            sb.Append(", Exception? exception = null");
        }
    }

    private static void AppendFieldArguments(
        StringBuilder sb,
        List<FieldDefinition> fields,
        bool hasException)
    {
        foreach (var field in fields)
        {
            sb.Append(", ");
            sb.Append(NamingHelper.ToCamelCase(field.Name));
        }

        if (hasException)
        {
            sb.Append(", exception");
        }
    }

    private static string GetInstrumentTypeName(MetricType metricType) => metricType switch
    {
        MetricType.Counter => "Counter",
        MetricType.Histogram => "Histogram",
        MetricType.Gauge => "Counter", // Simplified for now
        _ => "Counter"
    };

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
             .Replace("\"", "\\\"")
             .Replace("\n", "\\n")
             .Replace("\r", "\\r")
             .Replace("\t", "\\t")
             .Replace("\0", "\\0");

    private static string EscapeXmlComment(string value) =>
        value.Replace("&", "&amp;", StringComparison.Ordinal)
             .Replace("<", "&lt;", StringComparison.Ordinal)
             .Replace(">", "&gt;", StringComparison.Ordinal)
             .Replace("\"", "&quot;", StringComparison.Ordinal)
             .Replace("'", "&apos;", StringComparison.Ordinal);
}
