using System.Reflection;
using OtelEvents.Schema.CodeGen;
using OtelEvents.Schema.Models;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace OtelEvents.Schema.Tests;

/// <summary>
/// Tests for CodeGenerator — validates generated C# source code for events,
/// metrics, enums, and typed extension methods from schema definitions.
/// </summary>
public class CodeGeneratorTests
{
    private readonly CodeGenerator _generator = new();

    // ── Helper: minimal valid SchemaDocument ───────────────────────

    private static SchemaDocument CreateMinimalSchema(
        string name = "TestService",
        string ns = "Test.Events",
        string version = "1.0.0",
        string? meterName = null) => new()
    {
        Schema = new SchemaHeader
        {
            Name = name,
            Version = version,
            Namespace = ns,
            MeterName = meterName
        }
    };

    private static SchemaDocument CreateSchemaWithEvent(
        EventDefinition evt,
        string name = "TestService",
        string ns = "Test.Events",
        string? meterName = null) => new()
    {
        Schema = new SchemaHeader
        {
            Name = name,
            Version = "1.0.0",
            Namespace = ns,
            MeterName = meterName
        },
        Events = [evt]
    };

    // ═══════════════════════════════════════════════════════════════
    // 1. BASIC STRUCTURE
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void GenerateFromSchema_EmptySchema_ReturnsNoFiles()
    {
        var doc = CreateMinimalSchema();

        var files = _generator.GenerateFromSchema(doc);

        Assert.Empty(files);
    }

    [Fact]
    public void GenerateFromSchema_SchemaWithEvents_ReturnsEventsFile()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed"
        });

        var files = _generator.GenerateFromSchema(doc);

        Assert.Contains(files, f => f.FileName.EndsWith(".g.cs"));
    }

    [Fact]
    public void GenerateFromSchema_GeneratedCode_HasAutoGeneratedHeader()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed"
        });

        var files = _generator.GenerateFromSchema(doc);
        var eventsFile = files.First(f => f.FileName.Contains("Events"));

        Assert.Contains("<auto-generated>", eventsFile.Content);
        Assert.Contains("#nullable enable", eventsFile.Content);
    }

    [Fact]
    public void GenerateFromSchema_UsesNamespaceFromHeader()
    {
        var doc = CreateSchemaWithEvent(
            new EventDefinition
            {
                Name = "order.placed",
                Id = 1001,
                Severity = Severity.Info,
                Message = "Order {orderId} placed"
            },
            ns: "MyCompany.MyService.Events");

        var files = _generator.GenerateFromSchema(doc);
        var eventsFile = files.First(f => f.FileName.Contains("Events"));

        Assert.Contains("namespace MyCompany.MyService.Events;", eventsFile.Content);
    }

    [Fact]
    public void GenerateFromSchema_IncludesRequiredUsingStatements()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var eventsFile = files.First(f => f.FileName.Contains("Events"));

        Assert.Contains("using Microsoft.Extensions.Logging;", eventsFile.Content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 2. LOGGERMESSAGE PARTIAL METHODS
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_LoggerMessage_HasAttribute()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("[LoggerMessage(", content);
        Assert.Contains("EventId = 1001", content);
        Assert.Contains("Level = LogLevel.Information", content);
        Assert.Contains("\"Order {orderId} placed\"", content);
    }

    [Fact]
    public void Generate_LoggerMessage_IsPartialStaticMethod()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("public static partial void OrderPlaced(", content);
        Assert.Contains("this ILogger logger", content);
    }

    [Fact]
    public void Generate_LoggerMessage_ContainingClassIsStaticPartial()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed"
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("public static partial class TestServiceLoggerExtensions", content);
    }

    [Fact]
    public void Generate_LoggerMessage_WithMultipleFields()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed by {userId} for {amount}",
            Fields =
            [
                new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "userId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = true }
            ]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("string orderId", content);
        Assert.Contains("string userId", content);
        Assert.Contains("double amount", content);
    }

    [Fact]
    public void Generate_LoggerMessage_OptionalFieldsAreNullable()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields =
            [
                new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "userId", Type = FieldType.String, Required = false },
                new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = false }
            ]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("string? userId", content);
        Assert.Contains("double? amount", content);
    }

    [Fact]
    public void Generate_LoggerMessage_WithException_HasExceptionParameter()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.failed",
            Id = 1002,
            Severity = Severity.Error,
            Message = "Order {orderId} failed",
            Exception = true,
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("Exception? exception", content);
        Assert.Contains("Level = LogLevel.Error", content);
    }

    [Theory]
    [InlineData(Severity.Trace, "LogLevel.Trace")]
    [InlineData(Severity.Debug, "LogLevel.Debug")]
    [InlineData(Severity.Info, "LogLevel.Information")]
    [InlineData(Severity.Warn, "LogLevel.Warning")]
    [InlineData(Severity.Error, "LogLevel.Error")]
    [InlineData(Severity.Fatal, "LogLevel.Critical")]
    public void Generate_LoggerMessage_CorrectSeverityMapping(Severity severity, string expectedLogLevel)
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "test.event",
            Id = 2000,
            Severity = severity,
            Message = "Test event"
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains($"Level = {expectedLogLevel}", content);
    }

    [Fact]
    public void Generate_MultipleEvents_GeneratesAllMethods()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Events =
            [
                new EventDefinition
                {
                    Name = "order.placed",
                    Id = 1001,
                    Severity = Severity.Info,
                    Message = "Order placed"
                },
                new EventDefinition
                {
                    Name = "order.cancelled",
                    Id = 1002,
                    Severity = Severity.Warn,
                    Message = "Order cancelled"
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("OrderPlaced", content);
        Assert.Contains("OrderCancelled", content);
        Assert.Contains("EventId = 1001", content);
        Assert.Contains("EventId = 1002", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 3. ALL 12 C# TYPE MAPPINGS IN GENERATED CODE
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_AllFieldTypes_MappedCorrectly()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "types.test",
            Id = 9000,
            Severity = Severity.Info,
            Message = "Type test",
            Fields =
            [
                new FieldDefinition { Name = "strField", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "intField", Type = FieldType.Int, Required = true },
                new FieldDefinition { Name = "longField", Type = FieldType.Long, Required = true },
                new FieldDefinition { Name = "doubleField", Type = FieldType.Double, Required = true },
                new FieldDefinition { Name = "boolField", Type = FieldType.Bool, Required = true },
                new FieldDefinition { Name = "dateField", Type = FieldType.DateTime, Required = true },
                new FieldDefinition { Name = "durationField", Type = FieldType.Duration, Required = true },
                new FieldDefinition { Name = "guidField", Type = FieldType.Guid, Required = true },
                new FieldDefinition { Name = "strArrayField", Type = FieldType.StringArray, Required = true },
                new FieldDefinition { Name = "intArrayField", Type = FieldType.IntArray, Required = true },
                new FieldDefinition { Name = "mapField", Type = FieldType.Map, Required = true }
            ]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("string strField", content);
        Assert.Contains("int intField", content);
        Assert.Contains("long longField", content);
        Assert.Contains("double doubleField", content);
        Assert.Contains("bool boolField", content);
        Assert.Contains("DateTimeOffset dateField", content);
        Assert.Contains("TimeSpan durationField", content);
        Assert.Contains("Guid guidField", content);
        Assert.Contains("string[] strArrayField", content);
        Assert.Contains("int[] intArrayField", content);
        Assert.Contains("Dictionary<string, string> mapField", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 4. METER + COUNTER/HISTOGRAM GENERATION
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_Metrics_CreatesMeterWithCorrectName()
    {
        var doc = CreateSchemaWithEvent(
            new EventDefinition
            {
                Name = "order.placed",
                Id = 1001,
                Severity = Severity.Info,
                Message = "Order placed",
                Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter }]
            },
            meterName: "MyApp.Events.Orders");

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("new Meter(\"MyApp.Events.Orders\"", content);
    }

    [Fact]
    public void Generate_Metrics_DefaultMeterNameUsesNamespace()
    {
        var doc = CreateSchemaWithEvent(
            new EventDefinition
            {
                Name = "order.placed",
                Id = 1001,
                Severity = Severity.Info,
                Message = "Order placed",
                Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter }]
            },
            ns: "MyCompany.Orders");

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("new Meter(\"MyCompany.Orders\"", content);
    }

    [Fact]
    public void Generate_Metrics_Counter()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed",
            Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter, Unit = "requests" }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("Counter<long>", content);
        Assert.Contains("CreateCounter<long>(\"order.placed.count\"", content);
    }

    [Fact]
    public void Generate_Metrics_Histogram()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed",
            Metrics = [new MetricDefinition { Name = "order.placed.amount", Type = MetricType.Histogram, Unit = "USD" }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("Histogram<double>", content);
        Assert.Contains("CreateHistogram<double>(\"order.placed.amount\"", content);
    }

    [Fact]
    public void Generate_Metrics_ClassHasCorrectName()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed",
            Metrics = [new MetricDefinition { Name = "order.count", Type = MetricType.Counter }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("public static class TestServiceMetrics", content);
    }

    [Fact]
    public void Generate_Metrics_WithUnit()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "request.completed",
            Id = 2001,
            Severity = Severity.Info,
            Message = "Request completed",
            Metrics = [new MetricDefinition { Name = "request.duration", Type = MetricType.Histogram, Unit = "ms" }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("\"ms\"", content);
    }

    [Fact]
    public void Generate_Metrics_WithDescription()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "request.completed",
            Id = 2001,
            Severity = Severity.Info,
            Message = "Request completed",
            Metrics = [new MetricDefinition
            {
                Name = "request.count",
                Type = MetricType.Counter,
                Description = "Total requests processed"
            }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("\"Total requests processed\"", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 5. TYPED EMIT EXTENSION METHODS
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_EmitMethod_HasCorrectSignature()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }],
            Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("public static void EmitOrderPlaced(", content);
        Assert.Contains("this ILogger logger", content);
    }

    [Fact]
    public void Generate_EmitMethod_CallsLoggerMessageMethod()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }],
            Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("TestServiceLoggerExtensions.OrderPlaced(logger", content);
    }

    [Fact]
    public void Generate_EmitMethod_RecordsCounterMetric()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed",
            Metrics = [new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains(".Add(1", content);
    }

    [Fact]
    public void Generate_EmitMethod_RecordsHistogramMetric()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed for {amount}",
            Fields =
            [
                new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = true }
            ],
            Metrics = [new MetricDefinition { Name = "order.placed.amount", Type = MetricType.Histogram }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains(".Record(", content);
        // Should use the 'amount' field since metric name ends with 'amount'
        Assert.Contains("amount", content);
    }

    [Fact]
    public void Generate_EmitMethod_WithLabels_CreatesTagList()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields =
            [
                new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "region", Type = FieldType.String, Required = true }
            ],
            Metrics = [new MetricDefinition
            {
                Name = "order.placed.count",
                Type = MetricType.Counter,
                Labels = ["region"]
            }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("TagList", content);
        Assert.Contains("\"region\"", content);
    }

    [Fact]
    public void Generate_EmitMethod_WithoutMetrics_NoMetricCalls()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("EmitOrderPlaced", content);
        // Should still have the Emit method, just calling logger only
        Assert.Contains("TestServiceLoggerExtensions.OrderPlaced(logger", content);
    }

    [Fact]
    public void Generate_EmitMethod_ClassHasCorrectName()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed"
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("public static class TestServiceEventExtensions", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 6. ENUM GENERATION
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_Enum_GeneratesEnumType()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Enums =
            [
                new EnumDefinition
                {
                    Name = "order_status",
                    Values = ["Pending", "Completed", "Cancelled"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var enumFile = files.First(f => f.FileName.Contains("OrderStatus"));

        Assert.Contains("public enum OrderStatus", enumFile.Content);
        Assert.Contains("Pending", enumFile.Content);
        Assert.Contains("Completed", enumFile.Content);
        Assert.Contains("Cancelled", enumFile.Content);
    }

    [Fact]
    public void Generate_Enum_HasToStringFastExtension()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Enums =
            [
                new EnumDefinition
                {
                    Name = "http_method",
                    Values = ["GET", "POST", "PUT", "DELETE"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var enumFile = files.First(f => f.FileName.Contains("HttpMethod"));

        Assert.Contains("public static string ToStringFast(this HttpMethod value)", enumFile.Content);
        Assert.Contains("HttpMethod.GET => \"GET\"", enumFile.Content);
        Assert.Contains("HttpMethod.POST => \"POST\"", enumFile.Content);
    }

    [Fact]
    public void Generate_Enum_HasCorrectNamespace()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "MyCompany.Events"
            },
            Enums =
            [
                new EnumDefinition
                {
                    Name = "priority",
                    Values = ["Low", "Medium", "High"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var enumFile = files.First(f => f.FileName.Contains("Priority"));

        Assert.Contains("namespace MyCompany.Events;", enumFile.Content);
    }

    [Fact]
    public void Generate_Enum_WithDescription()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Enums =
            [
                new EnumDefinition
                {
                    Name = "severity_level",
                    Description = "Alert severity classification",
                    Values = ["Low", "Medium", "High", "Critical"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var enumFile = files.First(f => f.FileName.Contains("SeverityLevel"));

        Assert.Contains("Alert severity classification", enumFile.Content);
    }

    [Fact]
    public void Generate_InlineEnum_GeneratesEnumFile()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "request.completed",
            Id = 2001,
            Severity = Severity.Info,
            Message = "Request {method} completed",
            Fields =
            [
                new FieldDefinition
                {
                    Name = "method",
                    Type = FieldType.Enum,
                    Values = ["GET", "POST", "PUT", "DELETE"],
                    Required = true
                }
            ]
        });

        var files = _generator.GenerateFromSchema(doc);

        Assert.Contains(files, f => f.FileName.Contains("Method") && f.Content.Contains("public enum Method"));
    }

    [Fact]
    public void Generate_MultipleEnums_GeneratesSeparateFiles()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Enums =
            [
                new EnumDefinition { Name = "color", Values = ["Red", "Green", "Blue"] },
                new EnumDefinition { Name = "size", Values = ["Small", "Medium", "Large"] }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);

        Assert.Contains(files, f => f.FileName.Contains("Color"));
        Assert.Contains(files, f => f.FileName.Contains("Size"));
    }

    // ═══════════════════════════════════════════════════════════════
    // 7. TAGS AS METRIC LABELS
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_EventWithTags_TagsAvailableInEmitMethod()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order placed",
            Tags = ["commerce", "order"],
            Metrics = [new MetricDefinition { Name = "order.count", Type = MetricType.Counter }]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        // Tags referenced in the emit method
        Assert.Contains("EmitOrderPlaced", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 8. COMPREHENSIVE SCENARIO — FULL EVENT
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_FullEvent_AllComponentsPresent()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "OrderService",
                Version = "1.0.0",
                Namespace = "MyCompany.Orders.Events",
                MeterName = "MyCompany.Orders"
            },
            Enums =
            [
                new EnumDefinition { Name = "order_status", Values = ["Pending", "Completed", "Failed"] }
            ],
            Events =
            [
                new EventDefinition
                {
                    Name = "order.placed",
                    Id = 1001,
                    Severity = Severity.Info,
                    Message = "Order {orderId} placed by {userId} for {amount}",
                    Fields =
                    [
                        new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                        new FieldDefinition { Name = "userId", Type = FieldType.String, Required = true },
                        new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = true },
                        new FieldDefinition { Name = "status", Type = FieldType.Enum, Ref = "order_status", Required = true }
                    ],
                    Metrics =
                    [
                        new MetricDefinition { Name = "order.placed.count", Type = MetricType.Counter, Unit = "orders" },
                        new MetricDefinition { Name = "order.placed.amount", Type = MetricType.Histogram, Unit = "USD" }
                    ],
                    Tags = ["commerce", "order"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);

        // Should have: events file + enum file
        Assert.True(files.Count >= 2);

        var eventsFile = files.First(f => f.FileName.Contains("Events"));
        var enumFile = files.First(f => f.FileName.Contains("OrderStatus"));

        // Events file has all three classes
        Assert.Contains("OrderServiceLoggerExtensions", eventsFile.Content);
        Assert.Contains("OrderServiceMetrics", eventsFile.Content);
        Assert.Contains("OrderServiceEventExtensions", eventsFile.Content);

        // LoggerMessage
        Assert.Contains("[LoggerMessage(", eventsFile.Content);
        Assert.Contains("EventId = 1001", eventsFile.Content);
        Assert.Contains("Level = LogLevel.Information", eventsFile.Content);

        // Metrics
        Assert.Contains("new Meter(\"MyCompany.Orders\"", eventsFile.Content);
        Assert.Contains("CreateCounter<long>(\"order.placed.count\"", eventsFile.Content);
        Assert.Contains("CreateHistogram<double>(\"order.placed.amount\"", eventsFile.Content);

        // Emit method
        Assert.Contains("EmitOrderPlaced", eventsFile.Content);
        Assert.Contains("OrderStatus status", eventsFile.Content);

        // Enum file
        Assert.Contains("public enum OrderStatus", enumFile.Content);
        Assert.Contains("ToStringFast", enumFile.Content);
    }

    // ═══════════════════════════════════════════════════════════════
    // 9. GENERATED CODE COMPILES (ROSLYN VERIFICATION)
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_SimpleEvent_ProducesValidCSharpSyntax()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields = [new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true }]
        });

        var files = _generator.GenerateFromSchema(doc);

        foreach (var file in files)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(file.Content);
            var diagnostics = syntaxTree.GetDiagnostics().ToList();
            Assert.Empty(diagnostics);
        }
    }

    [Fact]
    public void Generate_FullEvent_ProducesValidCSharpSyntax()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "OrderService",
                Version = "1.0.0",
                Namespace = "MyCompany.Orders.Events",
                MeterName = "MyCompany.Orders"
            },
            Enums =
            [
                new EnumDefinition { Name = "payment_method", Values = ["CreditCard", "DebitCard", "PayPal", "BankTransfer"] }
            ],
            Events =
            [
                new EventDefinition
                {
                    Name = "payment.processed",
                    Id = 3001,
                    Severity = Severity.Info,
                    Message = "Payment {paymentId} processed via {method} for {amount}",
                    Exception = false,
                    Fields =
                    [
                        new FieldDefinition { Name = "paymentId", Type = FieldType.String, Required = true },
                        new FieldDefinition { Name = "method", Type = FieldType.Enum, Ref = "payment_method", Required = true },
                        new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = true },
                        new FieldDefinition { Name = "currency", Type = FieldType.String, Required = false }
                    ],
                    Metrics =
                    [
                        new MetricDefinition { Name = "payment.count", Type = MetricType.Counter },
                        new MetricDefinition
                        {
                            Name = "payment.amount",
                            Type = MetricType.Histogram,
                            Unit = "USD",
                            Labels = ["method"]
                        }
                    ],
                    Tags = ["payment", "finance"]
                },
                new EventDefinition
                {
                    Name = "payment.failed",
                    Id = 3002,
                    Severity = Severity.Error,
                    Message = "Payment {paymentId} failed: {reason}",
                    Exception = true,
                    Fields =
                    [
                        new FieldDefinition { Name = "paymentId", Type = FieldType.String, Required = true },
                        new FieldDefinition { Name = "reason", Type = FieldType.String, Required = true }
                    ],
                    Metrics =
                    [
                        new MetricDefinition { Name = "payment.failure.count", Type = MetricType.Counter }
                    ]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);

        foreach (var file in files)
        {
            var syntaxTree = CSharpSyntaxTree.ParseText(file.Content);
            var diagnostics = syntaxTree.GetDiagnostics().ToList();
            Assert.Empty(diagnostics);
        }
    }

    [Fact]
    public void Generate_FullEvent_ProducesCompilableCode()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "order.placed",
            Id = 1001,
            Severity = Severity.Info,
            Message = "Order {orderId} placed",
            Fields =
            [
                new FieldDefinition { Name = "orderId", Type = FieldType.String, Required = true },
                new FieldDefinition { Name = "amount", Type = FieldType.Double, Required = true }
            ],
            Metrics =
            [
                new MetricDefinition { Name = "order.count", Type = MetricType.Counter },
                new MetricDefinition { Name = "order.amount", Type = MetricType.Histogram }
            ]
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        var syntaxTree = CSharpSyntaxTree.ParseText(content);
        var references = GetCoreMetadataReferences();

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var diagnostics = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        // Partial methods with [LoggerMessage] can't fully compile without the source generator,
        // but all other code should have no errors beyond the partial method body.
        // Filter out CS8795 (partial method must have implementation) which is expected.
        var realErrors = diagnostics
            .Where(d => d.Id != "CS8795") // Partial method must have an implementation part
            .ToList();

        Assert.Empty(realErrors);
    }

    [Fact]
    public void Generate_EnumOnly_ProducesCompilableCode()
    {
        var doc = new SchemaDocument
        {
            Schema = new SchemaHeader
            {
                Name = "TestService",
                Version = "1.0.0",
                Namespace = "Test.Events"
            },
            Enums =
            [
                new EnumDefinition
                {
                    Name = "http_method",
                    Values = ["GET", "POST", "PUT", "DELETE", "PATCH"]
                }
            ]
        };

        var files = _generator.GenerateFromSchema(doc);
        var enumFile = files.First(f => f.FileName.Contains("HttpMethod"));

        var syntaxTree = CSharpSyntaxTree.ParseText(enumFile.Content);
        var references = GetCoreMetadataReferences();

        var compilation = CSharpCompilation.Create(
            "TestCompilation",
            [syntaxTree],
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        var errors = compilation.GetDiagnostics()
            .Where(d => d.Severity == DiagnosticSeverity.Error)
            .ToList();

        Assert.Empty(errors);
    }

    // ═══════════════════════════════════════════════════════════════
    // 10. EDGE CASES
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_EventWithNoFields_GeneratesMethodWithNoFieldParams()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "heartbeat.ping",
            Id = 9999,
            Severity = Severity.Debug,
            Message = "Heartbeat ping"
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("HeartbeatPing(this ILogger logger)", content);
    }

    [Fact]
    public void Generate_EventWithExceptionOnly_HasExceptionParam()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "unhandled.error",
            Id = 5000,
            Severity = Severity.Fatal,
            Message = "Unhandled error occurred",
            Exception = true
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.Contains("Exception? exception", content);
        Assert.Contains("Level = LogLevel.Critical", content);
    }

    [Fact]
    public void Generate_NoMetrics_DoesNotGenerateMetricsClass()
    {
        var doc = CreateSchemaWithEvent(new EventDefinition
        {
            Name = "simple.event",
            Id = 1000,
            Severity = Severity.Info,
            Message = "Simple event"
        });

        var files = _generator.GenerateFromSchema(doc);
        var content = files.First(f => f.FileName.Contains("Events")).Content;

        Assert.DoesNotContain("TestServiceMetrics", content);
        Assert.DoesNotContain("new Meter(", content);
    }

    // ═══════════════════════════════════════════════════════════════
    // Helper: Roslyn metadata references
    // ═══════════════════════════════════════════════════════════════

    private static MetadataReference[] GetCoreMetadataReferences()
    {
        var trustedAssemblies = ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
            .Split(Path.PathSeparator);

        var neededAssemblies = new[]
        {
            "System.Runtime",
            "System.Collections",
            "System.Diagnostics.DiagnosticSource",
            "Microsoft.Extensions.Logging.Abstractions",
            "netstandard",
            "System.Private.CoreLib"
        };

        return trustedAssemblies
            .Where(path => neededAssemblies.Any(name =>
                Path.GetFileNameWithoutExtension(path).Equals(name, StringComparison.OrdinalIgnoreCase)))
            .Select(path => MetadataReference.CreateFromFile(path))
            .ToArray<MetadataReference>();
    }
}
