using OtelEvents.Schema.Build;

namespace OtelEvents.Schema.Tests;

/// <summary>
/// Tests for <see cref="SchemaCodeGenRunner"/> — the orchestration logic that
/// parses .otel.yaml schema files, validates them, and generates C# source code.
/// </summary>
public sealed class SchemaCodeGenRunnerTests : IDisposable
{
    private readonly SchemaCodeGenRunner _runner = new();
    private readonly string _tempDir;
    private readonly string _outputDir;

    private const string ValidMinimalYaml = """
        schema:
          name: "TestService"
          version: "1.0.0"
          namespace: "Test.Events"
        """;

    private const string ValidYamlWithEvent = """
        schema:
          name: "TestService"
          version: "1.0.0"
          namespace: "Test.Events"
        events:
          order.placed:
            id: 1001
            severity: INFO
            message: "Order {orderId} placed"
            fields:
              orderId:
                type: string
                required: true
        """;

    private const string ValidYamlWithEventAndEnum = """
        schema:
          name: "TestService"
          version: "1.0.0"
          namespace: "Test.Events"
        enums:
          OrderStatus:
            values:
              - Pending
              - Confirmed
              - Shipped
        events:
          order.placed:
            id: 1001
            severity: INFO
            message: "Order {orderId} placed"
            fields:
              orderId:
                type: string
                required: true
        """;

    private const string InvalidYaml = """
        not_a_valid_schema: true
        """;

    private const string InvalidSchemaContent = """
        schema:
          name: "TestService"
          version: "not-semver!"
          namespace: "Test.Events"
        events:
          order.placed:
            id: 1001
            severity: INVALID_LEVEL
            message: "Order placed"
        """;

    public SchemaCodeGenRunnerTests()
    {
        _tempDir = Path.Combine(Path.GetTempPath(), $"codegen-runner-{Guid.NewGuid():N}");
        _outputDir = Path.Combine(_tempDir, "output");
        Directory.CreateDirectory(_tempDir);
    }

    public void Dispose()
    {
        if (Directory.Exists(_tempDir))
            Directory.Delete(_tempDir, true);
    }

    private string WriteSchemaFile(string content, string fileName = "events.otel.yaml")
    {
        var filePath = Path.Combine(_tempDir, fileName);
        File.WriteAllText(filePath, content);
        return filePath;
    }

    // ═══════════════════════════════════════════════════════════════
    // 1. SUCCESSFUL GENERATION
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_ValidSchemaWithEvent_ReturnsSuccess()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        Assert.Empty(result.Errors);
        Assert.NotEmpty(result.GeneratedFiles);
    }

    [Fact]
    public void Generate_ValidSchemaWithEvent_WritesGeneratedFiles()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        Assert.All(result.GeneratedFiles, path =>
        {
            Assert.True(File.Exists(path), $"Generated file should exist: {path}");
            Assert.EndsWith(".g.cs", path);
        });
    }

    [Fact]
    public void Generate_ValidSchemaWithEvent_GeneratedFilesContainCSharpCode()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        foreach (var filePath in result.GeneratedFiles)
        {
            var content = File.ReadAllText(filePath);
            Assert.Contains("// <auto-generated>", content);
            Assert.Contains("#nullable enable", content);
            Assert.Contains("namespace Test.Events", content);
        }
    }

    [Fact]
    public void Generate_ValidSchemaWithEventAndEnum_GeneratesMultipleFiles()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEventAndEnum);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        // Should have enum file + events file (at minimum)
        Assert.True(result.GeneratedFiles.Count >= 2,
            $"Expected at least 2 generated files, got {result.GeneratedFiles.Count}");
    }

    [Fact]
    public void Generate_ValidMinimalSchema_ReturnsSuccessWithNoFiles()
    {
        var schemaPath = WriteSchemaFile(ValidMinimalYaml);

        var result = _runner.Generate(schemaPath, _outputDir);

        // A schema with no events or enums generates no files — but it's still a success
        Assert.True(result.IsSuccess);
        Assert.Empty(result.Errors);
    }

    [Fact]
    public void Generate_CreatesOutputDirectory_WhenItDoesNotExist()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);
        var nestedOutput = Path.Combine(_tempDir, "nested", "deep", "output");

        var result = _runner.Generate(schemaPath, nestedOutput);

        Assert.True(result.IsSuccess);
        Assert.True(Directory.Exists(nestedOutput));
    }

    [Fact]
    public void Generate_OutputFilesAreInOutputDirectory()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        Assert.All(result.GeneratedFiles, path =>
        {
            Assert.StartsWith(_outputDir, path);
        });
    }

    [Fact]
    public void Generate_SetsSchemaFilePath()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.Equal(schemaPath, result.SchemaFilePath);
    }

    // ═══════════════════════════════════════════════════════════════
    // 2. PARSE ERRORS
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_InvalidYaml_ReturnsFailure()
    {
        var schemaPath = WriteSchemaFile(InvalidYaml);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.False(result.IsSuccess);
        Assert.NotEmpty(result.Errors);
        Assert.Empty(result.GeneratedFiles);
    }

    [Fact]
    public void Generate_NonexistentFile_ReturnsFailure()
    {
        var result = _runner.Generate("/nonexistent/schema.otel.yaml", _outputDir);

        Assert.False(result.IsSuccess);
        Assert.NotEmpty(result.Errors);
    }

    [Fact]
    public void Generate_EmptyFile_ReturnsFailure()
    {
        var schemaPath = WriteSchemaFile("");

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.False(result.IsSuccess);
        Assert.NotEmpty(result.Errors);
    }

    [Fact]
    public void Generate_InvalidSchemaContent_ReturnsFailure()
    {
        var schemaPath = WriteSchemaFile(InvalidSchemaContent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.False(result.IsSuccess);
        Assert.NotEmpty(result.Errors);
    }

    [Fact]
    public void Generate_FailedResult_ContainsErrorCodePrefix()
    {
        var schemaPath = WriteSchemaFile(InvalidYaml);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.False(result.IsSuccess);
        // Errors should contain the error code prefix (e.g., "OTEL_SCHEMA_xxx:")
        Assert.All(result.Errors, error => Assert.Contains(":", error));
    }

    [Fact]
    public void Generate_FailedResult_SetsSchemaFilePath()
    {
        var schemaPath = WriteSchemaFile(InvalidYaml);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.Equal(schemaPath, result.SchemaFilePath);
    }

    // ═══════════════════════════════════════════════════════════════
    // 3. INPUT VALIDATION
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_NullSchemaPath_ThrowsArgumentException()
    {
        Assert.ThrowsAny<ArgumentException>(() =>
            _runner.Generate(null!, _outputDir));
    }

    [Fact]
    public void Generate_EmptySchemaPath_ThrowsArgumentException()
    {
        Assert.ThrowsAny<ArgumentException>(() =>
            _runner.Generate("", _outputDir));
    }

    [Fact]
    public void Generate_NullOutputDirectory_ThrowsArgumentException()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        Assert.ThrowsAny<ArgumentException>(() =>
            _runner.Generate(schemaPath, null!));
    }

    [Fact]
    public void Generate_EmptyOutputDirectory_ThrowsArgumentException()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        Assert.ThrowsAny<ArgumentException>(() =>
            _runner.Generate(schemaPath, ""));
    }

    [Fact]
    public void Generate_WhitespaceSchemaPath_ThrowsArgumentException()
    {
        Assert.ThrowsAny<ArgumentException>(() =>
            _runner.Generate("   ", _outputDir));
    }

    // ═══════════════════════════════════════════════════════════════
    // 4. IDEMPOTENCY / OVERWRITE BEHAVIOR
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void Generate_CalledTwice_OverwritesExistingFiles()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result1 = _runner.Generate(schemaPath, _outputDir);
        Assert.True(result1.IsSuccess);

        // Modify timestamp to verify overwrite
        foreach (var file in result1.GeneratedFiles)
        {
            File.SetLastWriteTimeUtc(file, DateTime.UtcNow.AddHours(-1));
        }

        var result2 = _runner.Generate(schemaPath, _outputDir);
        Assert.True(result2.IsSuccess);

        // Files should have been rewritten (newer timestamp)
        foreach (var file in result2.GeneratedFiles)
        {
            var lastWrite = File.GetLastWriteTimeUtc(file);
            Assert.True(lastWrite > DateTime.UtcNow.AddMinutes(-1),
                "Generated file should have been overwritten with a recent timestamp");
        }
    }

    [Fact]
    public void Generate_MultipleSchemas_CanWriteToSameOutputDir()
    {
        var schema1 = WriteSchemaFile("""
            schema:
              name: "ServiceA"
              version: "1.0.0"
              namespace: "ServiceA.Events"
            events:
              service.a.started:
                id: 1001
                severity: INFO
                message: "Service A started"
            """, "serviceA.otel.yaml");

        var schema2 = WriteSchemaFile("""
            schema:
              name: "ServiceB"
              version: "1.0.0"
              namespace: "ServiceB.Events"
            events:
              service.b.started:
                id: 2001
                severity: INFO
                message: "Service B started"
            """, "serviceB.otel.yaml");

        var result1 = _runner.Generate(schema1, _outputDir);
        var result2 = _runner.Generate(schema2, _outputDir);

        Assert.True(result1.IsSuccess);
        Assert.True(result2.IsSuccess);

        // Output directory should contain files from both schemas
        var allFiles = Directory.GetFiles(_outputDir, "*.g.cs");
        Assert.True(allFiles.Length >= 2, "Output should contain files from both schemas");
    }

    // ═══════════════════════════════════════════════════════════════
    // 5. CODEGEN RESULT
    // ═══════════════════════════════════════════════════════════════

    [Fact]
    public void CodeGenResult_Succeeded_HasCorrectProperties()
    {
        var schemaPath = WriteSchemaFile(ValidYamlWithEvent);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.True(result.IsSuccess);
        Assert.Equal(schemaPath, result.SchemaFilePath);
        Assert.NotEmpty(result.GeneratedFiles);
        Assert.Empty(result.Errors);
    }

    [Fact]
    public void CodeGenResult_Failed_HasCorrectProperties()
    {
        var schemaPath = WriteSchemaFile(InvalidYaml);

        var result = _runner.Generate(schemaPath, _outputDir);

        Assert.False(result.IsSuccess);
        Assert.Equal(schemaPath, result.SchemaFilePath);
        Assert.Empty(result.GeneratedFiles);
        Assert.NotEmpty(result.Errors);
    }
}
