using System.Text;
using All.Schema.Models;

namespace All.Schema.CodeGen;

/// <summary>
/// Generates C# source code from a <see cref="SchemaDocument"/>.
/// Produces LoggerMessage extensions, metric instruments, typed Emit methods, and enum types.
/// </summary>
public sealed class CodeGenerator
{
    private const string AutoGeneratedHeader = """
        // <auto-generated>
        // Generated by ALL Code Generator
        // DO NOT EDIT — changes will be overwritten on next build
        // </auto-generated>
        
        #nullable enable
        
        """;

    /// <summary>
    /// Generates all C# source files from a schema document.
    /// </summary>
    /// <param name="doc">The parsed schema document.</param>
    /// <returns>A list of generated source files.</returns>
    public IReadOnlyList<GeneratedFile> GenerateFromSchema(SchemaDocument doc)
    {
        var files = new List<GeneratedFile>();

        // Collect all enums: top-level + inline from event fields
        var allEnums = CollectAllEnums(doc);
        foreach (var enumDef in allEnums)
        {
            files.Add(GenerateEnumFile(doc.Schema.Namespace, enumDef));
        }

        // Generate events file if there are events
        if (doc.Events.Count > 0)
        {
            files.Add(GenerateEventsFile(doc));
        }

        return files;
    }

    // ═══════════════════════════════════════════════════════════════
    // ENUM GENERATION
    // ═══════════════════════════════════════════════════════════════

    private static GeneratedFile GenerateEnumFile(string ns, EnumDefinition enumDef)
    {
        var enumName = NamingHelper.ToPascalCase(enumDef.Name);
        var sb = new StringBuilder();

        sb.Append(AutoGeneratedHeader);
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // Enum type
        if (enumDef.Description is not null)
        {
            sb.AppendLine($"/// <summary>{EscapeXmlComment(enumDef.Description)}</summary>");
        }
        sb.AppendLine($"public enum {enumName}");
        sb.AppendLine("{");
        foreach (var value in enumDef.Values)
        {
            var sanitized = NamingHelper.SanitizeIdentifier(value);
            sb.AppendLine($"    {sanitized},");
        }
        sb.AppendLine("}");
        sb.AppendLine();

        // ToStringFast extension
        sb.AppendLine($"/// <summary>Fast enum-to-string conversion (no allocation).</summary>");
        sb.AppendLine($"public static class {enumName}Extensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static string ToStringFast(this {enumName} value) => value switch");
        sb.AppendLine("    {");
        foreach (var value in enumDef.Values)
        {
            var sanitized = NamingHelper.SanitizeIdentifier(value);
            sb.AppendLine($"        {enumName}.{sanitized} => \"{EscapeString(value)}\",");
        }
        sb.AppendLine("        _ => value.ToString(),");
        sb.AppendLine("    };");
        sb.AppendLine("}");

        return new GeneratedFile($"{enumName}.g.cs", sb.ToString());
    }

    // ═══════════════════════════════════════════════════════════════
    // EVENTS FILE GENERATION
    // ═══════════════════════════════════════════════════════════════

    private static GeneratedFile GenerateEventsFile(SchemaDocument doc)
    {
        var schemaName = NamingHelper.SanitizeIdentifier(doc.Schema.Name);
        var ns = doc.Schema.Namespace;
        var meterName = doc.Schema.MeterName ?? ns;
        var hasAnyMetrics = doc.Events.Any(e => e.Metrics.Count > 0);

        var sb = new StringBuilder();
        sb.Append(AutoGeneratedHeader);

        // Using statements
        sb.AppendLine("using System;");
        if (hasAnyMetrics)
        {
            sb.AppendLine("using System.Diagnostics.Metrics;");
        }
        sb.AppendLine("using Microsoft.Extensions.Logging;");
        sb.AppendLine();

        // Namespace
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();

        // 1. LoggerMessage partial class
        GenerateLoggerExtensionsClass(sb, schemaName, doc.Events);
        sb.AppendLine();

        // 2. Metrics class (only if any event has metrics)
        if (hasAnyMetrics)
        {
            GenerateMetricsClass(sb, schemaName, meterName, doc);
            sb.AppendLine();
        }

        // 3. Emit extension methods class
        GenerateEventExtensionsClass(sb, schemaName, doc.Events, hasAnyMetrics);

        return new GeneratedFile($"{schemaName}Events.g.cs", sb.ToString());
    }

    // ── LoggerMessage Extensions ───────────────────────────────────

    private static void GenerateLoggerExtensionsClass(
        StringBuilder sb,
        string schemaName,
        List<EventDefinition> events)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// LoggerMessage methods for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static partial class {schemaName}LoggerExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < events.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            GenerateLoggerMessageMethod(sb, events[i]);
        }

        sb.AppendLine("}");
    }

    private static void GenerateLoggerMessageMethod(
        StringBuilder sb,
        EventDefinition evt)
    {
        var methodName = NamingHelper.ToMethodName(evt.Name);
        var logLevel = TypeMapper.ToLogLevel(evt.Severity);

        // [LoggerMessage] attribute
        sb.AppendLine($"    [LoggerMessage(");
        sb.AppendLine($"        EventId = {evt.Id},");
        sb.AppendLine($"        Level = {logLevel},");
        sb.AppendLine($"        Message = \"{EscapeString(evt.Message)}\")]");

        // Method signature
        sb.Append($"    public static partial void {methodName}(this ILogger logger");
        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");
    }

    // ── Metrics Class ──────────────────────────────────────────────

    private static void GenerateMetricsClass(
        StringBuilder sb,
        string schemaName,
        string meterName,
        SchemaDocument doc)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Metric instruments for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {schemaName}Metrics");
        sb.AppendLine("{");

        // Meter instance
        sb.AppendLine($"    private static readonly Meter s_meter = new Meter(\"{EscapeString(meterName)}\", \"{EscapeString(doc.Schema.Version)}\");");
        sb.AppendLine();

        var isFirst = true;
        foreach (var evt in doc.Events)
        {
            foreach (var metric in evt.Metrics)
            {
                if (!isFirst) sb.AppendLine();
                isFirst = false;

                GenerateMetricField(sb, metric);
            }
        }

        sb.AppendLine("}");
    }

    private static void GenerateMetricField(StringBuilder sb, MetricDefinition metric)
    {
        var clrType = TypeMapper.GetMetricClrType(metric.Type);
        var createMethod = TypeMapper.GetInstrumentCreationMethod(metric.Type);
        var fieldName = NamingHelper.ToMetricFieldName(metric.Name);
        var instrumentType = GetInstrumentTypeName(metric.Type);

        sb.Append($"    public static readonly {instrumentType}<{clrType}> {fieldName} =");
        sb.AppendLine();

        // Build creation call with optional unit and description
        sb.Append($"        s_meter.{createMethod}<{clrType}>(\"{EscapeString(metric.Name)}\"");

        if (metric.Unit is not null || metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Unit ?? "")}\"");
        }

        if (metric.Description is not null)
        {
            sb.Append($", \"{EscapeString(metric.Description)}\"");
        }

        sb.AppendLine(");");
    }

    // ── Event Extensions (Emit methods) ────────────────────────────

    private static void GenerateEventExtensionsClass(
        StringBuilder sb,
        string schemaName,
        List<EventDefinition> events,
        bool hasAnyMetrics)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine($"/// Typed extension methods combining logging and metrics for {schemaName} events.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine($"public static class {schemaName}EventExtensions");
        sb.AppendLine("{");

        for (var i = 0; i < events.Count; i++)
        {
            if (i > 0) sb.AppendLine();
            GenerateEmitMethod(sb, schemaName, events[i], hasAnyMetrics);
        }

        sb.AppendLine("}");
    }

    private static void GenerateEmitMethod(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt,
        bool hasAnyMetrics)
    {
        var methodName = NamingHelper.ToMethodName(evt.Name);
        var emitMethodName = $"Emit{methodName}";

        // Method signature
        sb.Append($"    public static void {emitMethodName}(this ILogger logger");
        AppendFieldParameters(sb, evt.Fields, evt.Exception);
        sb.AppendLine(")");
        sb.AppendLine("    {");

        // Call LoggerMessage method
        sb.Append($"        {schemaName}LoggerExtensions.{methodName}(logger");
        AppendFieldArguments(sb, evt.Fields, evt.Exception);
        sb.AppendLine(");");

        // Record metrics
        if (evt.Metrics.Count > 0)
        {
            sb.AppendLine();
            GenerateMetricRecording(sb, schemaName, evt);
        }

        sb.AppendLine("    }");
    }

    private static void GenerateMetricRecording(
        StringBuilder sb,
        string schemaName,
        EventDefinition evt)
    {
        // Build TagList if any metric has labels
        var hasLabels = evt.Metrics.Any(m => m.Labels is { Count: > 0 });
        if (hasLabels)
        {
            var allLabels = evt.Metrics
                .Where(m => m.Labels is not null)
                .SelectMany(m => m.Labels!)
                .Distinct()
                .ToList();

            sb.AppendLine("        var tags = new TagList");
            sb.AppendLine("        {");
            foreach (var label in allLabels)
            {
                var paramName = NamingHelper.ToCamelCase(NamingHelper.SanitizeIdentifier(label));
                sb.AppendLine($"            {{ \"{EscapeString(label)}\", {paramName} }},");
            }
            sb.AppendLine("        };");
        }

        foreach (var metric in evt.Metrics)
        {
            var fieldName = NamingHelper.ToMetricFieldName(metric.Name);
            var tagsSuffix = hasLabels && metric.Labels is { Count: > 0 } ? ", tags" : "";

            if (metric.Type == MetricType.Counter)
            {
                sb.AppendLine($"        {schemaName}Metrics.{fieldName}.Add(1{tagsSuffix});");
            }
            else if (metric.Type == MetricType.Histogram)
            {
                // Try to match a field by the last segment of the metric name
                var lastSegment = NamingHelper.GetLastSegment(metric.Name);
                var matchingField = evt.Fields.FirstOrDefault(f =>
                    f.Name.Equals(lastSegment, StringComparison.OrdinalIgnoreCase) &&
                    f.Type is not null &&
                    TypeMapper.IsNumericType(f.Type.Value));

                if (matchingField is not null)
                {
                    var paramName = NamingHelper.ToCamelCase(matchingField.Name);
                    var castPrefix = matchingField.Type != FieldType.Double ? "(double)" : "";
                    sb.AppendLine($"        {schemaName}Metrics.{fieldName}.Record({castPrefix}{paramName}{tagsSuffix});");
                }
                else
                {
                    sb.AppendLine($"        {schemaName}Metrics.{fieldName}.Record(1{tagsSuffix});");
                }
            }
        }
    }

    // ═══════════════════════════════════════════════════════════════
    // HELPERS
    // ═══════════════════════════════════════════════════════════════

    private static List<EnumDefinition> CollectAllEnums(SchemaDocument doc)
    {
        var enums = new List<EnumDefinition>(doc.Enums);
        var existingNames = new HashSet<string>(
            enums.Select(e => NamingHelper.ToPascalCase(e.Name)),
            StringComparer.Ordinal);

        foreach (var evt in doc.Events)
        {
            foreach (var field in evt.Fields)
            {
                if (field.Type == FieldType.Enum && field.Values is { Count: > 0 })
                {
                    var enumName = NamingHelper.ToPascalCase(field.Name);
                    if (existingNames.Add(enumName))
                    {
                        enums.Add(new EnumDefinition
                        {
                            Name = field.Name,
                            Values = field.Values
                        });
                    }
                }
            }
        }

        return enums;
    }

    private static void AppendFieldParameters(
        StringBuilder sb,
        List<FieldDefinition> fields,
        bool hasException)
    {
        foreach (var field in fields)
        {
            sb.Append(", ");
            var csharpType = TypeMapper.GetFieldCSharpType(field);
            var paramName = NamingHelper.ToCamelCase(field.Name);

            if (field.Required)
            {
                sb.Append($"{csharpType} {paramName}");
            }
            else
            {
                sb.Append($"{csharpType}? {paramName} = null");
            }
        }

        if (hasException)
        {
            sb.Append(", Exception? exception = null");
        }
    }

    private static void AppendFieldArguments(
        StringBuilder sb,
        List<FieldDefinition> fields,
        bool hasException)
    {
        foreach (var field in fields)
        {
            sb.Append(", ");
            sb.Append(NamingHelper.ToCamelCase(field.Name));
        }

        if (hasException)
        {
            sb.Append(", exception");
        }
    }

    private static string GetInstrumentTypeName(MetricType metricType) => metricType switch
    {
        MetricType.Counter => "Counter",
        MetricType.Histogram => "Histogram",
        MetricType.Gauge => "Counter", // Simplified for now
        _ => "Counter"
    };

    private static string EscapeString(string value) =>
        value.Replace("\\", "\\\\", StringComparison.Ordinal)
             .Replace("\"", "\\\"")
             .Replace("\n", "\\n")
             .Replace("\r", "\\r")
             .Replace("\t", "\\t")
             .Replace("\0", "\\0");

    private static string EscapeXmlComment(string value) =>
        value.Replace("&", "&amp;", StringComparison.Ordinal)
             .Replace("<", "&lt;", StringComparison.Ordinal)
             .Replace(">", "&gt;", StringComparison.Ordinal)
             .Replace("\"", "&quot;", StringComparison.Ordinal)
             .Replace("'", "&apos;", StringComparison.Ordinal);
}
