// <auto-generated/>
// Generated from schemas/orders.otel.yaml — do not edit manually.

#nullable enable

using System;
using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;
using OtelEvents.Causality;

namespace OtelEvents.Sample.WebApi.Events;

/// <summary>
/// Pre-compiled [LoggerMessage] methods and metrics for order lifecycle events.
/// Schema v3: PascalCase names, string event codes with ORDER prefix.
/// </summary>
internal static partial class OrderEvents
{
    // ─── Schema Metadata ────────────────────────────────────────────────

    /// <summary>The schema version from the YAML definition.</summary>
    public const string SchemaVersion = "3.0.0";

    /// <summary>The schema name from the YAML definition.</summary>
    public const string SchemaName = "Orders";

    // ─── Event Constants ────────────────────────────────────────────────

    /// <summary>Constants for the OrderPlaced event.</summary>
    public static class OrderPlaced
    {
        public const string Code = "ORDER-1000";
        public const int NumericId = 1000;
        public const string EventName = "OrderPlaced";
    }

    /// <summary>Constants for the OrderCompleted event.</summary>
    public static class OrderCompleted
    {
        public const string Code = "ORDER-1001";
        public const int NumericId = 1001;
        public const string EventName = "OrderCompleted";
    }

    /// <summary>Constants for the OrderFailed event.</summary>
    public static class OrderFailed
    {
        public const string Code = "ORDER-2000";
        public const int NumericId = 2000;
        public const string EventName = "OrderFailed";
    }

    /// <summary>Constants for the OrderNoteAdded event.</summary>
    public static class OrderNoteAdded
    {
        public const string Code = "ORDER-1002";
        public const int NumericId = 1002;
        public const string EventName = "OrderNoteAdded";
    }

    // ─── Meter & Instruments ────────────────────────────────────────────

    private static readonly Meter s_meter = new("Sample.Events.Orders", "3.0.0");

    internal static readonly Counter<long> OrderPlacedCount =
        s_meter.CreateCounter<long>("sample.order.placed.count", "orders", "Total orders placed");

    internal static readonly Histogram<double> OrderPlacedAmount =
        s_meter.CreateHistogram<double>("sample.order.placed.amount", "USD", "Order amount distribution");

    internal static readonly Counter<long> OrderFailedCount =
        s_meter.CreateCounter<long>("sample.order.failed.count", "errors", "Total order failures");

    // ─── Event: OrderPlaced (ID 1000, Code ORDER-1000) — type: start ────
    // Creates a causal scope + starts timer. Returns transaction handle.

    [LoggerMessage(
        EventId = 1000,
        EventName = "ORDER-1000",
        Level = LogLevel.Information,
        Message = "Order {OrderId} placed by {CustomerId} for ${Amount}")]
    private static partial void LogOrderPlaced(
        ILogger logger,
        string orderId,
        string customerId,
        string amount);

    /// <summary>
    /// Emits <c>OrderPlaced</c> (type: start) — creates a transaction scope.
    /// Dispose the returned handle to end the transaction.
    /// </summary>
    internal static OtelEventsTransactionScope BeginOrderPlaced(
        this ILogger logger,
        string orderId,
        string customerId,
        string amount)
    {
        LogOrderPlaced(logger, orderId, customerId, amount);

        OrderPlacedCount.Add(1,
            new KeyValuePair<string, object?>("customerId", customerId));

        if (double.TryParse(amount, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var amountValue))
            OrderPlacedAmount.Record(amountValue);

        return OtelEventsTransactionScope.Begin("OrderPlaced");
    }

    // ─── Event: OrderCompleted (ID 1001, Code ORDER-1001) — type: success ─
    // Closes parent scope (OrderPlaced) as success, records duration.

    [LoggerMessage(
        EventId = 1001,
        EventName = "ORDER-1001",
        Level = LogLevel.Information,
        Message = "Order {OrderId} shipped via {Carrier}")]
    private static partial void LogOrderCompleted(
        ILogger logger,
        string orderId,
        string carrier);

    /// <summary>
    /// Emits <c>OrderCompleted</c> (type: success) — closes the OrderPlaced transaction.
    /// </summary>
    internal static void EmitOrderCompleted(
        this ILogger logger,
        string orderId,
        string carrier)
    {
        LogOrderCompleted(logger, orderId, carrier);
        OtelEventsTransactionScope.TryComplete("OrderPlaced", "OrderCompleted");
    }

    // ─── Event: OrderFailed (ID 2000, Code ORDER-2000) — type: failure ──
    // Closes parent scope (OrderPlaced) as failure, records duration.

    [LoggerMessage(
        EventId = 2000,
        EventName = "ORDER-2000",
        Level = LogLevel.Error,
        Message = "Order {OrderId} failed: {Reason}")]
    private static partial void LogOrderFailed(
        ILogger logger,
        Exception exception,
        string orderId,
        string reason);

    /// <summary>
    /// Emits <c>OrderFailed</c> (type: failure) — closes the OrderPlaced transaction.
    /// </summary>
    internal static void EmitOrderFailed(
        this ILogger logger,
        string orderId,
        string reason,
        Exception exception)
    {
        LogOrderFailed(logger, exception, orderId, reason);
        OrderFailedCount.Add(1);
        OtelEventsTransactionScope.TryFail("OrderPlaced", "OrderFailed");
    }

    // ─── Event: OrderNoteAdded (ID 1002, Code ORDER-1002) — type: event ─
    // Plain event — no scope effect.

    [LoggerMessage(
        EventId = 1002,
        EventName = "ORDER-1002",
        Level = LogLevel.Information,
        Message = "Note added to order {OrderId}: {Note}")]
    private static partial void LogOrderNoteAdded(
        ILogger logger,
        string orderId,
        string note);

    /// <summary>
    /// Emits <c>OrderNoteAdded</c> (type: event) — standalone, no transaction effect.
    /// </summary>
    internal static void EmitOrderNoteAdded(
        this ILogger logger,
        string orderId,
        string note)
    {
        LogOrderNoteAdded(logger, orderId, note);
    }
}
