// <auto-generated/>
// Generated from schemas/orders.otel.yaml — do not edit manually.
// Re-generate with: dotnet run --project tools/OtelEvents.Cli -- generate schemas/orders.otel.yaml

#nullable enable

using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;

namespace OtelEvents.Sample.WebApi.Events;

/// <summary>
/// Pre-compiled [LoggerMessage] methods and metrics for order lifecycle events.
/// Maps to the orders.otel.yaml schema (event IDs 20001–20003).
/// </summary>
/// <remarks>
/// This code is pre-generated so the sample works out of the box without
/// needing the OtelEvents CLI tool installed.
/// </remarks>
internal static partial class OrderEvents
{
    // ─── Meter & Instruments ────────────────────────────────────────────

    private static readonly Meter s_meter = new("Sample.Events.Orders", "1.0.0");

    /// <summary>Counter: total orders placed, labeled by customerId.</summary>
    internal static readonly Counter<long> OrderPlacedCount =
        s_meter.CreateCounter<long>(
            "sample.order.placed.count", "orders", "Total orders placed");

    /// <summary>Histogram: order amount distribution in USD.</summary>
    internal static readonly Histogram<double> OrderPlacedAmount =
        s_meter.CreateHistogram<double>(
            "sample.order.placed.amount", "USD", "Order amount distribution");

    /// <summary>Counter: total order failures.</summary>
    internal static readonly Counter<long> OrderFailedCount =
        s_meter.CreateCounter<long>(
            "sample.order.failed.count", "errors", "Total order failures");

    // ─── Event: order.placed (ID 20001) ─────────────────────────────────

    [LoggerMessage(
        EventId = 20001,
        EventName = "order.placed",
        Level = LogLevel.Information,
        Message = "Order {OrderId} placed by customer {CustomerId} for ${Amount}")]
    private static partial void LogOrderPlaced(
        ILogger logger,
        string orderId,
        string customerId,
        double amount);

    /// <summary>
    /// Emits the <c>order.placed</c> event (ID 20001) and records metrics.
    /// </summary>
    internal static void OrderPlaced(
        this ILogger logger,
        string orderId,
        string customerId,
        double amount)
    {
        LogOrderPlaced(logger, orderId, customerId, amount);

        OrderPlacedCount.Add(1,
            new KeyValuePair<string, object?>("customerId", customerId));
        OrderPlacedAmount.Record(amount);
    }

    // ─── Event: order.completed (ID 20002) ──────────────────────────────

    [LoggerMessage(
        EventId = 20002,
        EventName = "order.completed",
        Level = LogLevel.Information,
        Message = "Order {OrderId} completed with status {Status}")]
    private static partial void LogOrderCompleted(
        ILogger logger,
        string orderId,
        string status);

    /// <summary>
    /// Emits the <c>order.completed</c> event (ID 20002).
    /// </summary>
    internal static void OrderCompleted(
        this ILogger logger,
        string orderId,
        string status)
    {
        LogOrderCompleted(logger, orderId, status);
    }

    // ─── Event: order.failed (ID 20003) ─────────────────────────────────

    [LoggerMessage(
        EventId = 20003,
        EventName = "order.failed",
        Level = LogLevel.Error,
        Message = "Order {OrderId} failed: {Reason}")]
    private static partial void LogOrderFailed(
        ILogger logger,
        Exception exception,
        string orderId,
        string reason);

    /// <summary>
    /// Emits the <c>order.failed</c> event (ID 20003) and records metrics.
    /// </summary>
    internal static void OrderFailed(
        this ILogger logger,
        string orderId,
        string reason,
        Exception exception)
    {
        LogOrderFailed(logger, exception, orderId, reason);

        OrderFailedCount.Add(1);
    }
}
