// <auto-generated/>
// Generated from schemas/orders.otel.yaml — do not edit manually.

#nullable enable

using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;
using OtelEvents.Causality;

namespace OtelEvents.Sample.WebApi.Events;

/// <summary>
/// Pre-compiled [LoggerMessage] methods and metrics for order lifecycle events.
/// Demonstrates typed transactions: start/success/failure/event patterns.
/// All fields are strings (simplified schema — Issue #42).
/// </summary>
internal static partial class OrderEvents
{
    // ─── Meter & Instruments ────────────────────────────────────────────

    private static readonly Meter s_meter = new("Sample.Events.Orders", "1.1.0");

    internal static readonly Counter<long> OrderPlacedCount =
        s_meter.CreateCounter<long>("sample.order.placed.count", "orders", "Total orders placed");

    internal static readonly Histogram<double> OrderPlacedAmount =
        s_meter.CreateHistogram<double>("sample.order.placed.amount", "USD", "Order amount distribution");

    internal static readonly Counter<long> OrderFailedCount =
        s_meter.CreateCounter<long>("sample.order.failed.count", "errors", "Total order failures");

    // ─── Event: order.placed (ID 20001) — type: start ───────────────────
    // Creates a causal scope + starts timer. Returns transaction handle.

    [LoggerMessage(
        EventId = 20001,
        EventName = "order.placed",
        Level = LogLevel.Information,
        Message = "Order {OrderId} placed by customer {CustomerId} for ${Amount}")]
    private static partial void LogOrderPlaced(
        ILogger logger,
        string orderId,
        string customerId,
        string amount);

    /// <summary>
    /// Emits <c>order.placed</c> (type: start) — creates a transaction scope.
    /// Dispose the returned handle to end the transaction.
    /// </summary>
    internal static OtelEventsTransactionScope BeginOrderPlaced(
        this ILogger logger,
        string orderId,
        string customerId,
        string amount)
    {
        LogOrderPlaced(logger, orderId, customerId, amount);

        OrderPlacedCount.Add(1,
            new KeyValuePair<string, object?>("customerId", customerId));

        if (double.TryParse(amount, System.Globalization.NumberStyles.Any, System.Globalization.CultureInfo.InvariantCulture, out var amountValue))
            OrderPlacedAmount.Record(amountValue);

        return OtelEventsTransactionScope.Begin("order.placed");
    }

    // ─── Event: order.completed (ID 20002) — type: success ──────────────
    // Closes parent scope (order.placed) as success, records duration.

    [LoggerMessage(
        EventId = 20002,
        EventName = "order.completed",
        Level = LogLevel.Information,
        Message = "Order {OrderId} shipped via {Carrier}")]
    private static partial void LogOrderCompleted(
        ILogger logger,
        string orderId,
        string carrier);

    /// <summary>
    /// Emits <c>order.completed</c> (type: success) — closes the order.placed transaction.
    /// </summary>
    internal static void OrderCompleted(
        this ILogger logger,
        string orderId,
        string carrier)
    {
        LogOrderCompleted(logger, orderId, carrier);
        OtelEventsTransactionScope.TryComplete("order.placed", "order.completed");
    }

    // ─── Event: order.failed (ID 20003) — type: failure ─────────────────
    // Closes parent scope (order.placed) as failure, records duration.

    [LoggerMessage(
        EventId = 20003,
        EventName = "order.failed",
        Level = LogLevel.Error,
        Message = "Order {OrderId} failed: {Reason}")]
    private static partial void LogOrderFailed(
        ILogger logger,
        Exception exception,
        string orderId,
        string reason);

    /// <summary>
    /// Emits <c>order.failed</c> (type: failure) — closes the order.placed transaction.
    /// </summary>
    internal static void OrderFailed(
        this ILogger logger,
        string orderId,
        string reason,
        Exception exception)
    {
        LogOrderFailed(logger, exception, orderId, reason);
        OrderFailedCount.Add(1);
        OtelEventsTransactionScope.TryFail("order.placed", "order.failed");
    }

    // ─── Event: order.note.added (ID 20004) — type: event (default) ─────
    // Plain event — no scope effect.

    [LoggerMessage(
        EventId = 20004,
        EventName = "order.note.added",
        Level = LogLevel.Information,
        Message = "Note added to order {OrderId}: {Note}")]
    private static partial void LogOrderNoteAdded(
        ILogger logger,
        string orderId,
        string note);

    /// <summary>
    /// Emits <c>order.note.added</c> (type: event) — standalone, no transaction effect.
    /// </summary>
    internal static void OrderNoteAdded(
        this ILogger logger,
        string orderId,
        string note)
    {
        LogOrderNoteAdded(logger, orderId, note);
    }
}
